initial registration
JIA-0302/TipTracker pull request #50
Opened 2021-02-17 14:48 UTC by gsuStudent

added registration page

2021-02-17 15:42 UTC, ibaniya98 requested changes
Form looks good!

2021-02-17 15:42 UTC, ibaniya98 commented on components/registration/index.tsx
> +        userId: 0,
nit: There is no need for `userId` in the registration screen since they don't have one and will be assigned later on the registration flow.

2021-02-17 15:42 UTC, ibaniya98 commented on pages/registration.tsx
> +        <PrivateLayout>
We can use a separate Layout for authentication screens. The idea of using `PrivateLayout` is it will contain all pages that should only be visible to logged-in user and will automatically redirect any unauthenticated user to the login page.

You can create a new Layout `AuthLayout` under  `component/layouts/auth-layout`. This will take `children` as props and render it. 
For the new layout, we can just copy over `/pages/index.tsx` contents . It will have logo on the side, and simply pass `children` in place of `main` component.

https://github.com/JIA-0302/TipTracker/blob/17c6c3d8caa22965509b62b30b961f37b97be808/pages/index.tsx#L26

2021-02-17 16:39 UTC, vrajp13 submitted a review, later dismissed
Looking good

2021-02-17 17:03 UTC, cpc2820 approved these changes, later dismissed
Looks solid to me!

2021-02-18 00:11 UTC, Nepal-6D48A0 approved these changes
Looking good. You might have to merge the main to your PR first.

2021-02-18 00:27 UTC, merged